import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
	container: {
		paddingBottom: 28,
	},
	successToast: {
		position: 'absolute',
		top: 0,
		left: 0,
		right: 0,
		zIndex: 100,
		padding: 14,
		alignItems: 'center',
	},
	successToastText: {
		color: '#FFFFFF',
		fontWeight: '800',
		fontSize: 15,
	},
	hero: {
		paddingHorizontal: 18,
		paddingTop: 18,
		paddingBottom: 72,
		borderBottomLeftRadius: 28,
		borderBottomRightRadius: 28,
	},
	heroTopRow: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
	},
	avatarRow: {
		flex: 1,
		flexDirection: 'row',
		alignItems: 'center',
		minWidth: 0,
	},
	avatar: {
		width: 50,
		height: 50,
		borderRadius: 25,
		alignItems: 'center',
		justifyContent: 'center',
		borderWidth: 1,
		borderColor: 'rgba(255,255,255,0.22)',
	},
	avatarInitials: {
		fontSize: 18,
		fontWeight: '900',
		color: '#FFFFFF',
	},
	heroCopy: {
		flex: 1,
		marginLeft: 12,
		minWidth: 0,
	},
	eyebrow: {
		color: 'rgba(255,255,255,0.74)',
		fontSize: 12,
		fontWeight: '700',
		marginBottom: 3,
	},
	welcome: {
		color: '#FFFFFF',
		fontSize: 25,
		lineHeight: 29,
		fontWeight: '900',
	},
	topActions: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 8,
	},
	iconBtn: {
		width: 38,
		height: 38,
		borderRadius: 14,
		backgroundColor: 'rgba(255,255,255,0.14)',
		borderWidth: 1,
		borderColor: 'rgba(255,255,255,0.2)',
		alignItems: 'center',
		justifyContent: 'center',
	},
	accessRow: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 8,
		marginTop: 16,
	},
	subtitleBadge: {
		alignSelf: 'flex-start',
		paddingHorizontal: 11,
		paddingVertical: 7,
		borderRadius: 999,
		backgroundColor: 'rgba(255,255,255,0.13)',
		borderWidth: 1,
		borderColor: 'rgba(255,255,255,0.18)',
	},
	subtitle: {
		color: '#FFFFFF',
		fontSize: 12,
		fontWeight: '800',
	},
	planBadge: {
		alignSelf: 'flex-start',
		paddingHorizontal: 10,
		paddingVertical: 7,
		borderRadius: 999,
		backgroundColor: '#FFFFFF',
	},
	planText: {
		color: '#000',
		fontSize: 11,
		fontWeight: '900',
	},
	todayCard: {
		marginHorizontal: 18,
		marginTop: -52,
		borderRadius: 22,
		padding: 16,
		borderWidth: 1,
		borderColor: 'rgba(23,32,42,0.06)',
		shadowOpacity: 0.14,
		shadowRadius: 18,
		shadowOffset: { width: 0, height: 10 },
		elevation: 4,
	},
	sectionHeader: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		marginBottom: 12,
	},
	sectionTitle: {
		fontSize: 17,
		fontWeight: '900',
	},
	sectionLink: {
		fontSize: 12,
		fontWeight: '900',
	},
	todayGrid: {
		flexDirection: 'row',
		flexWrap: 'wrap',
		gap: 10,
	},
	todayMetric: {
		width: '48%',
		borderRadius: 16,
		paddingVertical: 12,
		paddingHorizontal: 12,
		backgroundColor: '#F8FBFA',
		borderWidth: 1,
		borderColor: '#D9E2EC',
	},
	todayValue: {
		fontSize: 23,
		fontWeight: '900',
		marginBottom: 2,
	},
	todayLabel: {
		fontSize: 12,
		fontWeight: '800',
	},
	eventBox: {
		marginHorizontal: 18,
		marginTop: 16,
		marginBottom: 0,
		borderRadius: 22,
		padding: 14,
		flexDirection: 'row',
		alignItems: 'flex-start',
		borderWidth: 1,
		borderColor: 'rgba(23,32,42,0.06)',
		shadowOpacity: 0.08,
		shadowRadius: 14,
		shadowOffset: { width: 0, height: 8 },
		elevation: 2,
	},
	eventText: {
		fontSize: 17,
		fontWeight: '900',
	},
	eventRow: {
		paddingVertical: 6,
		marginRight: 6,
	},
	eventRowTitle: {
		fontSize: 14,
		fontWeight: '800',
	},
	eventRowSubtitle: {
		fontSize: 12,
		marginTop: 2,
		fontWeight: '600',
	},
	propertyCard: {
		marginHorizontal: 18,
		marginTop: 16,
		borderRadius: 22,
		overflow: 'hidden',
		borderWidth: 1,
		borderColor: 'rgba(23,32,42,0.06)',
		shadowOpacity: 0.1,
		shadowRadius: 18,
		shadowOffset: { width: 0, height: 10 },
		elevation: 3,
	},
	propertyVisual: {
		height: 126,
		backgroundColor: '#CFE0DA',
		overflow: 'hidden',
	},
	propertyHouseShape: {
		position: 'absolute',
		left: 78,
		bottom: -18,
		width: 176,
		height: 104,
		borderRadius: 16,
		backgroundColor: '#F7EFE3',
		transform: [{ rotate: '-4deg' }],
		borderWidth: 1,
		borderColor: 'rgba(20,92,83,0.12)',
	},
	statusPill: {
		position: 'absolute',
		top: 12,
		right: 12,
		borderRadius: 999,
		paddingHorizontal: 10,
		paddingVertical: 6,
		backgroundColor: '#EDF8F1',
		borderWidth: 1,
		borderColor: 'rgba(46,139,87,0.18)',
	},
	statusPillText: {
		color: '#333',
		fontSize: 11,
		fontWeight: '900',
		textTransform: 'capitalize',
	},
	propertyBody: {
		padding: 14,
	},
	propertyTitleRow: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		gap: 10,
		marginBottom: 12,
	},
	propertyTitleCopy: {
		flex: 1,
		minWidth: 0,
	},
	propertyTitle: {
		fontSize: 17,
		fontWeight: '900',
		marginBottom: 3,
	},
	propertyAddress: {
		fontSize: 12,
		fontWeight: '700',
	},
	propertyRevenue: {
		fontSize: 13,
		fontWeight: '900',
	},
	nextVisitBox: {
		borderRadius: 16,
		backgroundColor: '#F6F9F8',
		borderWidth: 1,
		borderColor: '#D9E2EC',
		padding: 11,
	},
	nextVisitLabel: {
		fontSize: 11,
		fontWeight: '800',
		marginBottom: 3,
	},
	nextVisitValue: {
		fontSize: 13,
		fontWeight: '900',
	},
	summaryContainer: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		width: '100%',
		marginBottom: 20,
	},
	summaryGrid: {
		width: '100%',
	},
	summaryRow: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		marginBottom: 8,
	},
	summaryBox: {
		flex: 1,
		marginHorizontal: 6,
		borderRadius: 10,
		paddingVertical: 12,
		paddingHorizontal: 6,
		alignItems: 'center',
		elevation: 1,
		minWidth: 0,
	},
	summaryLabel: {
		fontSize: 13,
		marginBottom: 2,
	},
	summaryValue: {
		fontSize: 18,
		fontWeight: 'bold',
		textAlign: 'center',
	},
	quickActionsGrid: {
		width: '100%',
		marginBottom: 20,
	},
	quickActionsRow: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		width: '100%',
		marginBottom: 12,
	},
	actionBtn: {
		flex: 1,
		marginHorizontal: 5,
		borderRadius: 10,
		paddingVertical: 18,
		paddingHorizontal: 8,
		alignItems: 'center',
		justifyContent: 'center',
		elevation: 2,
	},
	centerContent: {
		flexDirection: 'column',
		alignItems: 'center',
		justifyContent: 'center',
	},
	icon: {
		marginBottom: 8,
	},
	actionText: {
		fontSize: 16,
		fontWeight: 'bold',
		textAlign: 'center',
	},
});
